# Site settings
email: info@sdv.ml
# url: https://sdv.ml
url: https://sdvml.github.io

description: "A collection of open source frameworks for synthetic data generation."
keywords: "synthetic data, machine learning, deep learning, generative adversarial networks"
title: "Synthetic Data Vault"
meta_author: Data to AI Laboratory
logo: SDV-logo-short.png

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

header:
  background: data-center-2.jpg
  background-white: data-center-2-white.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: 18bc9c #80B3FF
  # primary: fafafa
  light: fafafa
  primary: 2c3e50
  primary-dark: 233140 #A2122F
  # primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  yellow: e2de60

# Footer settings
footer:
  copyright: MIT Data To AI Lab
  # location: Location
  social: Resources
  credits: Credits

resources:
  github: http://github.com/HDI-Project/SDV
  book: https://hdi-project.github.io/SDV/
  stack-overflow: http://stackoverflow.com/questions/tagged/sdv

resources:
  - title: GitHub
    icon: github
    url: http://github.com/HDI-Project/SDV
  - title: Documentation
    icon: book
    url: https://hdi-project.github.io/SDV/
  - title: Stack Overflow
    icon: stack-overflow
    url: http://stackoverflow.com/questions/tagged/sdv

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'SDV is an open source project from <a href="https://dai.lids.mit.edu/">Data to AI Lab at MIT</a>.'

# Build settings
markdown: kramdown
permalink: pretty
