# Site settings
email: info@sdv.ml
# url: https://sdv.ml
url: https://sdvml.github.io

description: "A collection of open source frameworks for synthetic data generation"
keywords: "synthetic data, machine learning, deep learning, generative adversarial networks"
title: "Synthetic Data Vault"
meta_author: MIT Data To AI Lab
logo: SDV-logo-short.png

header:
  background: data-center-2.jpg
  background-white: data-center-2-white.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: 18bc9c #80B3FF
  # primary: fafafa
  light: fafaff
  primary: e2de60
  primary-dark: 233140 #A2122F
  # primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  yellow: e2de60

font:
  text: Lato,"Helvetica Neue",Helvetica,Arial,sans-serif;
  header: Lato Bold,"Helvetica Neue",Helvetica,Arial,sans-serif;

# Footer settings
footer:
  copyright: MIT Data To AI Lab
  social: Resources
  credits: Credits

links:
  github: http://github.com/HDI-Project/SDV
  book: https://hdi-project.github.io/SDV/
  stack-overflow: http://stackoverflow.com/questions/tagged/sdv
  paper: https://dai.lids.mit.edu/wp-content/uploads/2018/03/SDV.pdf

resources:
  - title: GitHub
    icon: github
    url: http://github.com/HDI-Project/SDV
  - title: Documentation
    icon: book
    url: https://hdi-project.github.io/SDV/
  - title: Stack Overflow
    icon: stack-overflow
    url: http://stackoverflow.com/questions/tagged/sdv

# Credits content
credits: 'SDV is an open source project from <a href="https://dai.lids.mit.edu/">Data to AI Lab at MIT</a>.'

# Build settings
markdown: kramdown
permalink: pretty
